### ISSUE TITLE
ETP-238: Fix Errors in Tests for copilot Modules

### ISSUE THREAD

**Issue by valenvivaldi** [etendosoftware/com.etendoerp.copilot.extensions#10]
### Issue Description

There are two issues in the tests of the following modules:

com.etendoerp.copilot.toolpack and com.etendoerp.copilot.openapi.purchase, which are causing the CI/CD pipelines to fail. These issues need to be investigated and resolved:

Dependency on the pypdfium library in com.etendoerp.copilot.toolpack.

Problem with AttachTool in com.etendoerp.copilot.openapi.purchase.

### Solution Design

In the **com.etendoerp.copilot.toolpack** module, review the dependency on the pypdfium library to determine if it is necessary or if it can be replaced by using an already generated file.

In the **com.etendoerp.copilot.openapi.purchase** module, investigate and fix the problem with **AttachTool**.

### Use Cases

pypdfium Dependency in **com.etendoerp.copilot.toolpack**

Given: The **com.etendoerp.copilot.toolpack** module relies on the **pypdfium** library.

When: Reviewing the current implementation for pypdfium usage.

Then: Determine if the library is essential. If not, refactor to use an already generated file instead and ensure the CI/CD pipelines do not fail.

Issue with **AttachTool** in **com.etendoerp.copilot.openapi.purchase**

Given: The **com.etendoerp.copilot.openapi.purchase** module has a problem with the **AttachTool**, causing tests to fail.

When: Running the tests that involve **AttachTool**

- Then: Identify the issue, fix the error, and ensure all tests pass without causing CI/CD pipelines to fail.

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.4.1](https://github.com/etendosoftware/com.etendoerp.copilot.extensions/releases/tag/1.4.1) ⚡ 🚀
