### ISSUE TITLE
Correct the erroneous reading of the environment variable ETENDO_HOST within the Copilot Docker container.

### ISSUE THREAD

**Issue by valenvivaldi** [etendosoftware/com.etendoerp.copilot.extensions#13]
# Issue Description
The current implementation of the Copilot Docker container incorrectly reads the environment variable ETENDO_HOST, leading to potential misconfigurations and operational issues. This variable is critical for the proper functioning of services relying on it.
# Solution Design
Investigate the code responsible for reading environment variables within the Docker container and identify why ETENDO_HOST is being read incorrectly.
Implement a fix to correctly read and use the ETENDO_HOST variable.
Test the change to ensure that ETENDO_HOST is now being read correctly and that normal operations are restored.
# Use Cases
Given: The Copilot Docker container is running with the environment variable ETENDO_HOST set.
When: The container or related services attempt to access the ETENDO_HOST variable.
Then: The value of ETENDO_HOST should be accurately read and used by the service, ensuring proper configuration and operation.

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.5.1](https://github.com/etendosoftware/com.etendoerp.copilot.extensions/releases/tag/1.5.1) ⚡ 🚀
