### ISSUE TITLE
ETP-384: Fix the Issue with URLs Breaking When Sending Very Long Texts

### ISSUE THREAD

**Issue by valenvivaldi** [etendosoftware/com.etendoerp.copilot.extensions#14]
# Issue Description

The client has reported an issue where sending very long texts results in broken URLs. This disrupts the user experience as the URLs are not clickable and may cause errors in the interface.

# Solution Design

Modify the text handling function to ensure that very long texts do not cause URLs to break. This might involve:

Implementing URL shortening for long URLs.

Implementing word wrap logic that ensures URLs remain intact.

Testing edge cases with various lengths of text and URLs to ensure robustness.

# Use Cases

Given: The user inputs a very long text with an embedded URL.

When: The user sends the text.

Then: The system should ensure the URL remains unbroken and fully functional.

Given: The system receives a text with multiple URLs.

When: The text is being processed.

Then: All URLs within the text should remain clickable and not break irrespective of the text length.

Given: The system processes a text with long continuous strings.

When: Rendering the text.

Then: Ensure the URL does not break and that the UI handles the text gracefully without errors.

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.6.2](https://github.com/etendosoftware/com.etendoerp.copilot.extensions/releases/tag/1.6.2) ⚡ 🚀
