### ISSUE TITLE
ETP-460: Etendo copilot subapp doesn't continue conversations

### ISSUE THREAD

**Issue by sebastianbarrozo** [etendosoftware/com.etendoerp.copilot.extensions#16]
# Error's Description

There is an issue with the Etendo Copilot subapp where every time a question is asked, a new conversation is initiated. The conversation should be continuous until the window is restarted.

# Steps to Reproduce the Error

## Required Configurations

Install the Copilot subapp and its dependencies.

Enable an assistant within the application.

Greet the assistant by saying: "Hello, my name is John."

Wait for the assistant's response.

Ask the assistant: "What is my name?"

## Expected Behavior

The assistant should remember the previous conversation context and respond with "Your name is John," rather than resetting the conversation.

## Affected Version

Latest/Specific? Version number: 1.0.0

# Solution Design

In first message conversation is received , keep it and send on each request . In case of reload or Assistant change, must reset and start a new conversation.

# Other Test Cases

Given: The Copilot subapp is installed and configured properly. 

When: A user engages in a conversation with the assistant. 

Then: The assistant should maintain the conversation context throughout the interaction until the window is closed or restarted.

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.7.0](https://github.com/etendosoftware/com.etendoerp.copilot.extensions/releases/tag/1.7.0) ⚡ 🚀
