### ISSUE TITLE
ETP-519: No assistant works in Copilot, the question is not found.

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/com.etendoerp.copilot.extensions#19]
# Error's description
In the latest version of Copilot, none of the assistants are functional. When attempting to communicate, the system does not respond as expected.

 # Steps to reproduce the error

 ### Required Configurations (if necessary)
Ensure all assistants are configured and synchronized.

1. Open the Copilot interface.
2. Attempt to communicate using a greeting such as "hi" with any assitant.

Log Error
The following error is visible in the environment log:
ERROR com.etendoerp.copilot.rest.RestService - org.openbravo.base.exception.OBException: Error handling question: Missing question in request

 # Expected behavior
The assistants should recognize the input and respond appropriately according to their configuration and functionality.

 # Affected Version
 ¿Latest/Specific?
Latest
 Version number:
Copilot.extensions 1.6.0

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.6.2](https://github.com/etendosoftware/com.etendoerp.copilot.extensions/releases/tag/1.6.2) ⚡ 🚀
