### ISSUE TITLE
[ETP-583] Restrict XML Translator Assistant to System App Only

### ISSUE THREAD

**Issue by valenvivaldi** [etendosoftware/com.etendoerp.copilot.extensions#21]
**Issue Description**

The XML Translator Assistant app currently functions as a general application. However, the requirement is to restrict it so that it operates only as a system application, ensuring that it cannot be used or accessed as a regular application. This is required to enhance security and control over its usage.

**Solution Design**

Develop a mechanism to identify the application's context of operation and restrict it exclusively for system-level operations.

Implement access controls that will prevent the app from launching if attempted to be used outside the predefined system environment.

Ensure the app only runs when initialized by system processes and not by user-initiated processes.

**Use Cases**

**Given:** The XML Translator Assistant is installed on the system.

**When:** A general user attempts to launch the application.

**Then:** The application should not start and display an access restricted message.

**Given:** The system initiates the XML Translator Assistant.

**When:** The app is summoned by a system-level process.

**Then:** The application should launch and operate normally without restrictions.

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.7.1](https://github.com/etendosoftware/com.etendoerp.copilot.extensions/releases/tag/1.7.1) ⚡ 🚀
