### ISSUE TITLE
[ETP-586] Copilot chat is stuck in “Processing”

### ISSUE THREAD

**Issue by fran-roig** [etendosoftware/com.etendoerp.copilot.extensions#22]
# Error's description
Copilot chat is stuck in “Processing” when asking something. It shows an error in the copilot docker log:
HTTP Request: POST https://api.openai.com/v1/threads/runs "HTTP/1.1 401 Unauthorized".
This happens on an instance that previously had working assistants and now the api_key changed or is deprecated.

 # Steps to reproduce the error
Sync error:
1. Open a new chat with any assistant
2. Type anything

 ### Required Configurations (if necessary)
An instance with previously synced assistants
An incorrect OPENAI_API_KEY in the gradle.properties

 # Expected behavior
Copilot chat should inform the user that the OPENAI_API_KEY is not valid

 # Affected Version
Etendo Core: 24.3.1
com.etendoerp.copilot.extensions 1.7.0

 # Solution Design (optional)

 # Other test cases
 **Given:**
 **When:**
 **Then:**

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.7.3](https://github.com/etendosoftware/com.etendoerp.copilot.extensions/releases/tag/1.7.3) ⚡ 🚀
