### ISSUE TITLE
ETP-644: Copilot cache validation failure 

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/com.etendoerp.copilot.extensions#23]
# Error's description
In the latest version of Copilot, when interacting with the wizards no answers are obtained, a new validation added in the latest release is launched in the log.
`2024-10-29 08:36:36,494 [http-nio-8080-exec-4] ERROR com.etendoerp.copilot.rest.RestService - org.codehaus.jettison.json.JSONException: Cached question is null.`

 # Steps to reproduce the error
1. Synchronize SQL Expert
2. Open a conversation
3. Write "Hello".

 # Expected behavior
Copilot should get the question and continue the conversation.

 # Affected Version
com.etendoetp.copilot.extensions 1.7.1
Module: com.etendoerp.copilot 1.8.1

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.7.2](https://github.com/etendosoftware/com.etendoerp.copilot.extensions/releases/tag/1.7.2) ⚡ 🚀
