### ISSUE TITLE
[ETP-730] Copilot gradle tasks run, even if Copilot's docker mode is not enabled

### ISSUE THREAD

**Issue by valenvivaldi** [etendosoftware/com.etendoerp.copilot.extensions#26]
### Error's description
When executing compilation and restart gradle task  with Copilot installed but not enabled ( docker_com.etendoerp.copilot=false in gradle.properties), the tasks of copilot executes anyways.

- If executes the task "smartbuild", the task "copilot.restart" is executed, even if the docker_com.etendoerp.copilot is false

- If executes the task "resources.up", the task "copilot.build" is executed, even if the docker_com.etendoerp.copilot is false

- If executes the task "generateEnvFile", the task "copilot.env.file" is executed, even if the docker_com.etendoerp.copilot is falseSteps to reproduce the error

### Steps to reproduce the error
Required Configurations (if necessary)
Ensure all necessary resources are started, except Copilot.

Verify that Copilot's Docker container is installed, but not with docker mode enabled.

Execute

./gradlew smartbuild --dry-run

check that the task copilot build is planified to execute

### Expected behavior
- If executes the task "smartbuild" must executes the task 'copilot.build', only if the docker_com.etendoerp.copilot is true

- If executes the task "resources.up" must executes the task 'copilot.build', only if the docker_com.etendoerp.copilot is true

- If executes the task "generateEnvFile" must executes the task 'copilot.env.file', only if the docker_com.etendoerp.copilot is true

### Affected Version
Latest Version number: Current version

### Solution Design (optional)
The solution should restrict the addition of the copilot tasks by the value of docker_com.etendoerp.copilot

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.8.1](https://github.com/etendosoftware/com.etendoerp.copilot.extensions/releases/tag/1.8.1) ⚡ 🚀
