### ISSUE TITLE
ETP-770: Open AI type wizards get stuck in “Processing”

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/com.etendoerp.copilot.extensions#27]
# Error's description
The copilot chat gets stuck on “Processing” when asking something to an OpenAI type assistant.
This happens in the case of an unsynchronized wizard, for example.

 # Steps to reproduce the error
Sync error:
1. In a clean environment (not in demo) go to the Enterprise Module management window and install the Etendo Copilot dataset.
2. Go to the assistants window and check that this is Bastian (do not synchronize it).
3. In the Assistant Access window, give access to the current role
4. Open a new chat and select Bastian
5. Say “Hello“.

 # Expected behavior
The error should be displayed and not remain processing in the interface.

 # Affected Version
Latest
Version number: Copilot Extensions 1.8.1

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.8.3](https://github.com/etendosoftware/com.etendoerp.copilot.extensions/releases/tag/1.8.3) ⚡ 🚀
