### ISSUE TITLE
ETP-774: Error in the message displayed when not having an assistant synchronized in Copilot.

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/com.etendoerp.copilot.extensions#28]
# Error's description
When we want to access from the copilot pop-up to an assistant that was never synchronized, we get an error. It says that you must update the assistant in the Copilot App window, which is actually called Assistant.

 # Steps to reproduce the error
1. Enter Etendo
2. Look in the "Assistant" window for any that are not synchronized
3. Go to the copilot pop-up
4. Select that assistant
5. Ask a question

https://github.com/user-attachments/assets/4050be33-c4da-4ca7-ac1a-842f7ababe23

 # Expected behavior
The message should say: "The assistant is not synchronized. Synchronize the assistant in the assistant window and try again."

 # Affected Version
com.etendoerp:copilot.extensions:1.8.0

 # Solution Design (optional)
Modify the message instead of saying "Copilot App" window, it should be "Assistant".
Also, you should check that "Copilot App" is not used in other instances, in which case it should be corrected if necessary.

 # Other test cases
 **Given:**
 **When:**
 **Then:**

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.8.3](https://github.com/etendosoftware/com.etendoerp.copilot.extensions/releases/tag/1.8.3) ⚡ 🚀
