### ISSUE TITLE
ETP-841: Visual error when running copilot gradle tasks.

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/com.etendoerp.copilot.extensions#29]
# Error's description
When running a Gradle task, the log message "Copying Copilot files" appears in Spanish, which should be in English.
![image](https://github.com/user-attachments/assets/4e7f5382-9407-4475-8cf8-9a5f7f8e85cf)

 # Steps to reproduce the error
Install Copilot.
Run any Gradle task.

 # Expected behavior
The log message should appear as "Copying Copilot files".

 # Affected Version
Version number: 1.8.0 ('com.etendoerp:copilot.extensions:1.8.0')

 # Solution Design (optional)
Modify the Gradle build script to ensure that the log message appears in English, changing "Copying Copilot files" to "Copying Copilot files".

 # Other test cases
 **Given:**
 **When:**
 **Then:**

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.8.4](https://github.com/etendosoftware/com.etendoerp.copilot.extensions/releases/tag/1.8.4) ⚡ 🚀
