### ISSUE TITLE
ETP-843: Exporting additional information from copilot.

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/com.etendoerp.copilot.extensions#31]
# Error's description
When running an export.config.script from a custom template, the user gets additional information from Copilot, related to the sync status. Specifically, the issue is that the sync_status column is being exported by mistake. This column should not be exported and should be set to "Pending Sync" by default.

 # Steps to reproduce the error
1. Use a specific wizard that generates code (for example, the "Create Event Handler" wizard).
2. Run an export.config.script.
3. Note that, instead of generating only what is necessary, it includes information related to the wizard's settings, such as the sync status.

 # Expected behavior
During the export process, only the necessary information created by the user should be generated, without including internal Copilot settings, such as the sync_status column.

 # Affected Version
Specific: Yes
Version Number: Copilot Bundle v1.8.0 (com.etendoerp:copilot.extensions:1.8.0)

 # Solution Design (optional)
The column sync_status is being exported by mistake. This column should not be part of the export and should be set by default to "Pending Sync".

 # Other test cases
 **Given:**
 **When:**
 **Then:**

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.8.4](https://github.com/etendosoftware/com.etendoerp.copilot.extensions/releases/tag/1.8.4) ⚡ 🚀
