### ISSUE TITLE
ETP-844: Problems when requesting the wizard to create a table of type view.

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/com.etendoerp.copilot.extensions#32]
# Error's description
In the table creation wizard, when specifying that the table is of type "view," the system does not handle this configuration correctly.

 # Steps to reproduce the error

1. Access the table creation wizard from the Copilot pop-up.
2. Select the table creation wizard.
3. Specify the creation of a "view" type table.

 # Expected behavior
When selecting a "view" type table in the wizard:
The table should be correctly created and marked as a "view" in the database and the application.

 # Affected Version
Version Number: Copilot Bundle v1.8.0 (com.etendoerp:copilot.extensions:1.8.0)Solution Design (optional)

 # Solution Design (optional)

 # Other test cases
 **Given:**
 **When:**
 **Then:**

**Comment by valeg-etendo** [comment]
This issue is not a bug but a new feature that will be available in the next release of Copilot Extensions which will be 1.9.0.
