### ISSUE TITLE
[ETP-881] Fix Import Issues in Copilot UI Build

### ISSUE THREAD

**Issue by valenvivaldi** [etendosoftware/com.etendoerp.copilot.extensions#35]
# Error's description
When executing a Yarn Build on the main branch of Copilot to build the UI, the process fails due to problems with imports.

 # Solution Design (optional)
Identify and correct the incorrect import statements in the codebase for the UI component of Copilot.

Use Cases
 **Given:**: The developer is on the main branch of the Copilot codebase.

 **When:**: The developer runs the Yarn Build command.

 **Then:**: The build process should complete successfully without import errors.

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.8.4](https://github.com/etendosoftware/com.etendoerp.copilot.extensions/releases/tag/1.8.4) ⚡ 🚀
