### ISSUE TITLE
EE-1018: Problem on file capacity limit for an copilot app with code intepreter

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/com.etendoerp.copilot.extensions#4]
# Error's description
When a record in the "Copilot App" window has the "code interpreter" checkbox checked and more than 20 files are associated to it in the level 1 tab, when trying to synchronize, an array length error occurs. This happens because a wizard with "code interpreter" only supports up to 20 related files.

# Steps to reproduce the error
  1. Install copilot beforehand as explained in the guide on the Etendo wiki.
  2. Create a simple record in the "copilot app" window which is of type "OpenAI assitant".
  3. Check the "code interpreter" checkbox and save.
  4. Create for example 21 records in the "copilot file" window, all of which must be of type "Attached File". To these I will attach a sample .pdf file.
  5. Now, associate these 21 files in the "copilot app" created in step 2. The Behaviour is “[Copilot App] Add to the assistant as Knowledge Base“
  6. In “copilot app“ run sync openai assitant.
# Expected behavior
You should be able to synchronize correctly regardless of the number of files.
  
# Affected Version
¿ Latest/Specific ? Latest
Version number: com.etendoerp.copilot 1.3.0 in bundle com.etendoerp.copilot.extensions
  
# Solution Design (optional)
  In the file records in the "copilot app" window, it is possible to differentiate between those used for "code interpreter" and those used for "retrieval".

**Comment by isaiasb-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.2.2](https://github.com/etendosoftware/com.etendoerp.copilot.extensions/releases/tag/1.2.2).
