### ISSUE TITLE
EML-598: Copilot not booting in the last version

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/com.etendoerp.copilot.extensions#8]
**Error's description**
Upon installing the bundle com.etendoerp.copilot.extensions version 1.3.0 released last week, an error occurs upon its initiation. This is due to certain tools’ packages being unable to install and “attempt to import” their libraries. Consequently, the container cannot start, and Copilot cannot be utilized.

**Steps to reproduce the error**
1. Download and install the bundle com.etendoerp.copilot.extensions version 1.3.0
2. Attempt to initiate Copilot.

**Expected behavior**
The expected behavior is that Copilot should start and be usable even if certain tools’ libraries cannot be installed. Ideally, the installation check should not “throw an exception” if a library cannot be installed, allowing Copilot to operate at least without that specific tool. Additionally, the tools should properly define the required packages for installation.

**Affected version**
.Latest
.Version number: 1.3.0

**Solution Design (optional)**
Modify the installation check mechanism in the module com.etendoerp.copilot so that it does not throw an exception if a library cannot be installed, thus enabling Copilot to be used even without that particular tool.

Ensure that the modules com.etendoerp.copilot.toolpack and com.etendoerp.copilot.ocrtool correctly specify the required packages to avoid installation failures.

**Other Test Cases**

Given: An environment where com.etendoerp.copilot.extensions version 1.3.0 is installed
When: The user attempts to initiate Copilot
Then: Copilot should start without throwing an exception due to missing libraries, even if certain tools are not fully operational.

**Comment by isaiasb-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.3.1](https://github.com/etendosoftware/com.etendoerp.copilot.extensions/releases/tag/1.3.1).
