### ISSUE TITLE
ETP-128: Copilot App not recognizing HQL Query as knowledge base

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/com.etendoerp.copilot.extensions#9]
# Error's description
We are experiencing a problem with the latest version of Copilot. When a Copilot file of type HQL query is created, we know that a CSV file is generated internally. However, when this Copilot file is added to a Copilot application on the App Source tab as a knowledge base, it is not recognized.

# Steps to reproduce the error
1. Create a Copilot File of type HQL Query. (anything query of example)
2. Add this Copilot File to the App Source tab as a knowledge base in a Copilot App.
3. Sync
4. Ask this copilot about the information that should be included in the query.

# Expected behavior
It should recognize the hql query (its result) as a knowledge base.

# Affected Version
Latest

Copilot 1.3.1

# Solution Design (optional)

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.3.2](https://github.com/etendosoftware/com.etendoerp.copilot.extensions/releases/tag/1.3.2).
